-- Idempotent migration: safe to run manually in Supabase SQL Editor.
create table if not exists public.quiz_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  result text not null,
  answers jsonb not null,
  locale text not null,
  created_at timestamptz not null default now()
);

-- Optional: add an index for common lookups by email/locale if needed in production.
-- create index if not exists quiz_submissions_email_idx on public.quiz_submissions (email);

-- Note: RLS is intentionally not enabled here.
-- Enable it in production if you need row-level access control:
-- alter table public.quiz_submissions enable row level security;
